In [20]:
import pandas as pd
import numpy as np
import random

In [2]:
df = pd.read_csv("csv_files/StudentsPerformance.csv")

In [22]:
clone_df = df.copy()

In [24]:
new_index = np.arange(0, 1000)

In [25]:
np.random.shuffle(new_index)

In [27]:
clone_df["new index"] = new_index

In [28]:
clone_df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,new index
0,female,group B,bachelor's degree,standard,none,72,72,74,463
1,female,group C,some college,standard,completed,69,90,88,584
2,female,group B,master's degree,standard,none,90,95,93,236
3,male,group A,associate's degree,free/reduced,none,47,57,44,894
4,male,group C,some college,standard,none,76,78,75,451

In [32]:
clone_df.set_index(new_index)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,new index
463,female,group B,bachelor's degree,standard,none,72,72,74,463
584,female,group C,some college,standard,completed,69,90,88,584
236,female,group B,master's degree,standard,none,90,95,93,236
894,male,group A,associate's degree,free/reduced,none,47,57,44,894
451,male,group C,some college,standard,none,76,78,75,451
...,...,...,...,...,...,...,...,...,...
388,female,group E,master's degree,standard,completed,88,99,95,388
106,male,group C,high school,free/reduced,none,62,55,55,106
877,female,group C,high school,free/reduced,completed,59,71,65,877
114,female,group D,some college,standard,completed,68,78,77,114
428,female,group D,some college,free/reduced,none,77,86,86,428

In [30]:
clone_df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,new index
0,female,group B,bachelor's degree,standard,none,72,72,74,463
1,female,group C,some college,standard,completed,69,90,88,584
2,female,group B,master's degree,standard,none,90,95,93,236
3,male,group A,associate's degree,free/reduced,none,47,57,44,894
4,male,group C,some college,standard,none,76,78,75,451
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,388
996,male,group C,high school,free/reduced,none,62,55,55,106
997,female,group C,high school,free/reduced,completed,59,71,65,877
998,female,group D,some college,standard,completed,68,78,77,114
999,female,group D,some college,free/reduced,none,77,86,86,428