In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("csv_files/StudentsPerformance.csv")

### Rename

##### it usuage:
1. renaming column
2. renaming index like index 0 to A, 1 to b ....

In [13]:
clone_df = df.copy()
clone_df.head()

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

#### Renaming cloumn using rename method

In [14]:
## renaming using method
clone_df.rename(columns= {"gender" : "Gender", "race/ethnicity": "Race"}).head(3)

,Gender,Race,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93

#### renaming index using rename with index parameters

In [16]:
clone_df.rename(index= {0 : "A", 1 : "B", 3: "C"}).head(5)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
A,female,group B,bachelor's degree,standard,none,72,72,74
B,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
C,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [ ]:
# note it doesnt not work on whole index it olly work on selected index